### ISSUE TITLE
Environment variables conflict, CF_API_KEY(CLOUDFLARE)  vs CF_API_KEY(itzg/minecraft-server)

### ISSUE THREAD

**Issue by Zombely** [MyShlongIsLongAT/docker-ncfs-minecraft-server#1]
## Issue Overview:
This bug arises from a conflict in environment variable names, specifically involving CF_API_KEY, within the Dockerfile and init-ncfs.sh script. The clash occurs between the Cloudflare API key variable (CF_API_KEY) and a similarly named variable introduced by the itzg/minecraft-server image.

## Affected Components:

Dockerfile
init-ncfs.sh script

## Error Description:
The issue manifests as an ambiguity in the interpretation of the CF_API_KEY environment variable, leading to failed startup when using curseforge auto download.

**Comment by FlorianBreuker** [comment]
@Zombely sorry for that late response. going to have a look on it in this week. happy new year :)

**Comment by FlorianBreuker** [comment]
I have tested the script now and pushed the latest version to GH. Hope it finds its use.
