### ISSUE TITLE
Change NGROK settings

### ISSUE THREAD

**Issue by ac1mx** [MyShlongIsLongAT/docker-ncfs-minecraft-server#2]
I'm looking for a way to change the NGROK settings, specifically, I want to tell NGROK to bind to a port on the Docker container's network, so I can access the NGROK status page from the host. I found the ngrok.yml file, and I was able to modify it, however, it seems that the file is regenerated each time the server starts, meaning that any changes I make are erased when the ngrok,yml file is renewed. Is there a way to change the ngrok.yml file permanently? Thanks!

**Comment by FlorianBreuker** [comment]
have you tried it with docker volumes?
