### ISSUE TITLE
Question on Ngrok

### ISSUE THREAD

**Issue by MedChicken** [MyShlongIsLongAT/docker-ncfs-minecraft-server#3]
Sorry for an old necro, but I've used Ngrok previously, but hit the free data usage limit, does this docker-ncfs-minecraft-server's usage of the Ngrok url add up to the ngrok data transfer usage? Or is it just the use of a url?

**Comment by FlorianBreuker** [comment]
Hi MedChicken,

sorry for my late response.

According to this [guide](https://ngrok.com/docs/guides/limits/) transfer limits get a reset every month.

"An endpoint is any device, app, or API that connects to a computer network. When you put an app online at foo.ngrok-free.app (using your free static domain), that’s one endpoint. If you connect to a device using a TCP protocol at 9.67.1.100, that’s another endpoint."

"This is the number of bytes you are transmitting out of your endpoints."

From my point of view, I think, that the traffic going out from your container is counting as bandwidth for ngrok.

I did no testing until now.

Hope I could help.
